# Generated by Django 5.2.5 on 2025-12-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustrialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., CNC Machine', max_length=200)),
                ('category', models.CharField(choices=[('manufacturing', 'Manufacturing Machinery'), ('construction', 'Construction Equipment'), ('power_tools', 'Power Tools'), ('material_handling', 'Material Handling'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(help_text='Detailed product description')),
                ('short_description', models.CharField(help_text='Brief description for cards', max_length=300)),
                ('image_url', models.URLField(help_text='Paste image URL here', max_length=500)),
                ('features', models.TextField(help_text='Comma separated features')),
                ('specifications', models.TextField(blank=True, help_text='Technical specifications')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_active', models.BooleanField(default=True, help_text='Show on website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
            ],
            options={
                'verbose_name': 'Industrial Product',
                'verbose_name_plural': 'Industrial Products',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlywoodProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 4x4 Feet Plywood Sheets', max_length=200)),
                ('description', models.TextField(help_text='Detailed product description')),
                ('short_description', models.CharField(help_text='Brief description for cards', max_length=300)),
                ('image_url', models.URLField(help_text='Paste image URL here', max_length=500)),
                ('size', models.CharField(blank=True, help_text='e.g., 4x4 Feet (1220x1220mm)', max_length=100)),
                ('thickness', models.CharField(blank=True, help_text='e.g., 6mm to 25mm', max_length=100)),
                ('grade', models.CharField(blank=True, help_text='e.g., BWR, BWP, MR', max_length=100)),
                ('features', models.TextField(help_text='Comma separated features')),
                ('applications', models.CharField(blank=True, help_text='e.g., Furniture, Construction', max_length=300)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_active', models.BooleanField(default=True, help_text='Show on website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
            ],
            options={
                'verbose_name': 'Plywood Product',
                'verbose_name_plural': 'Plywood Products',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 1121 Golden Premium Sella Rice', max_length=200)),
                ('description', models.TextField(help_text='Detailed product description')),
                ('short_description', models.CharField(help_text='Brief description for cards', max_length=300)),
                ('image_url', models.URLField(help_text='Paste image URL here', max_length=500)),
                ('origin', models.CharField(default='India', help_text='e.g., Punjab & Haryana, India', max_length=100)),
                ('grain_length', models.CharField(blank=True, help_text='e.g., 8.3mm+', max_length=50)),
                ('features', models.TextField(help_text='Comma separated features, e.g., Long Grain, Aromatic, Non-Sticky')),
                ('best_for', models.CharField(blank=True, help_text='e.g., Biryani, Pulao, Premium Dishes', max_length=300)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_active', models.BooleanField(default=True, help_text='Show on website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
            ],
            options={
                'verbose_name': 'Rice Product',
                'verbose_name_plural': 'Rice Products',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyShoeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Steel Toe Safety Boots', max_length=200)),
                ('shoe_type', models.CharField(choices=[('steel_toe', 'Steel Toe Boots'), ('low_cut', 'Low-Cut Safety Shoes'), ('composite', 'Composite Toe Shoes'), ('waterproof', 'Waterproof Boots'), ('other', 'Other')], default='steel_toe', max_length=50)),
                ('description', models.TextField(help_text='Detailed product description')),
                ('short_description', models.CharField(help_text='Brief description for cards', max_length=300)),
                ('image_url', models.URLField(help_text='Paste image URL here', max_length=500)),
                ('features', models.TextField(help_text='Comma separated features')),
                ('sizes_available', models.CharField(blank=True, help_text='e.g., UK 5-13', max_length=100)),
                ('certifications', models.CharField(blank=True, help_text='e.g., EN ISO 20345, ASTM F2413', max_length=200)),
                ('best_for', models.CharField(blank=True, help_text='e.g., Construction, Manufacturing', max_length=300)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_active', models.BooleanField(default=True, help_text='Show on website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
            ],
            options={
                'verbose_name': 'Safety Shoe Product',
                'verbose_name_plural': 'Safety Shoe Products',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Cinnamon (Dalchini)', max_length=200)),
                ('description', models.TextField(help_text='Detailed product description')),
                ('short_description', models.CharField(help_text='Brief description for cards', max_length=300)),
                ('image_url', models.URLField(help_text='Paste image URL here', max_length=500)),
                ('origin', models.CharField(default='India', help_text='e.g., Kerala, India', max_length=100)),
                ('features', models.TextField(help_text='Comma separated features')),
                ('uses', models.CharField(blank=True, help_text='e.g., Curries, Biryani, Garam Masala', max_length=300)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_active', models.BooleanField(default=True, help_text='Show on website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
            ],
            options={
                'verbose_name': 'Spice Product',
                'verbose_name_plural': 'Spice Products',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactEnquiry',
        ),
        migrations.AlterModelOptions(
            name='contactenquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Enquiry', 'verbose_name_plural': 'Contact Enquiries'},
        ),
    ]
